project:
  upload-url: ./images/
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/text
    username: root
    password: 123456
#  data:
#    redis:
#      host: 127.0.0.1
#      port: 6379
##      password: yannqing
#      database: 0
#      lettuce:
#        pool:
#          max-active: 8
#          max-wait: 1
#          max-idle: 8
#          min-idle: 0
#      timeout: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

